input_data_path: "data/raw/heart.csv"
target_name: "target"
splitting_params:
  test_size: 0.25
  random_state: 33
train_params:
  model_type: "LogisticRegression"
dump_model: "models/model.pkl"
